/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author User01
 */
public class ADMINCERTIFICATE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ADMINCERTIFICATE.class.getName());

    /**
     * Creates new form ADMINCERTIFICATE
     */
   public ADMINCERTIFICATE(String fullname) {
    setContentPane(new BackgrounPanel()); // reuse
    initComponents();
    loadCertificateRequests();
    
     
 // ================= STATUS COLOR =================
certTable.getColumnModel().getColumn(5).setCellRenderer(
new DefaultTableCellRenderer(){

    @Override
    public java.awt.Component getTableCellRendererComponent(
            javax.swing.JTable table,
            Object value,
            boolean isSelected,
            boolean hasFocus,
            int row,
            int column){

        java.awt.Component c =
        super.getTableCellRendererComponent(
                table,
                value,
                isSelected,
                hasFocus,
                row,
                column
        );

        String status = value.toString();

        if(status.equalsIgnoreCase("Pending")){

            c.setForeground(Color.RED);

        }else if(status.equalsIgnoreCase("Done")){

            c.setForeground(new Color(0,128,0));

        }else{

            c.setForeground(Color.BLACK);
        }

        return c;
    }
}
);
    }
   
public void loadCertificateRequests(){

try{

Connection con = DBConnection.getConnection();

String sql = "SELECT * FROM certificate_requests";

PreparedStatement pst = con.prepareStatement(sql);
ResultSet rs = pst.executeQuery();

DefaultTableModel model = (DefaultTableModel)certTable.getModel();
model.setRowCount(0);

while(rs.next()){

model.addRow(new Object[]{
rs.getString("fullname"),
rs.getString("address"),
rs.getString("purok"),
rs.getString("certificate_type"),
rs.getString("purpose"),
rs.getString("status")
});

}

}catch(Exception e){
System.out.println(e);
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        certTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(856, 534));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logo_barangay1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("CERTIFICATE");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("ADMIN DASHBOARD -> CERTIFICATE");

        certTable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        certTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FULLNAME", "ADDRESS", "PUROK", "CERTIFICATE TYPE", "PURPOSE", "STATUS"
            }
        ));
        certTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                certTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(certTable);

        JTextArea.setColumns(20);
        JTextArea.setRows(5);
        jScrollPane2.setViewportView(JTextArea);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("DONE");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("PRINT");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(425, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addContainerGap(395, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(233, 233, 233))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int row = certTable.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(null, "Please select a request first.");
    return;
}

String fullname = certTable.getValueAt(row, 0).toString();
String address  = certTable.getValueAt(row, 1).toString();
String purok    = certTable.getValueAt(row, 2).toString();
String type     = certTable.getValueAt(row, 3).toString();
String purpose  = certTable.getValueAt(row, 4).toString();

try{

    Connection con = DBConnection.getConnection();

    // ================= UPDATE STATUS =================
    String sql = "UPDATE certificate_requests SET status='Done' WHERE fullname=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, fullname);

    pst.executeUpdate();


    // ================= AUTO CONTROL NUMBER =================
    String controlNo = "2026-" + (1000 + row);


    // ================= AUTO DATE =================
    Date date = new Date();

    SimpleDateFormat fullDate =
            new SimpleDateFormat("MMMM dd, yyyy");

    String dateIssued = fullDate.format(date);

    SimpleDateFormat dayFormat =
            new SimpleDateFormat("dd");

    String day = dayFormat.format(date);

    SimpleDateFormat monthYearFormat =
            new SimpleDateFormat("MMMM yyyy");

    String monthYear = monthYearFormat.format(date);



    // ================= REPORT =================
    JTextArea report = new JTextArea();

    report.setText(

    "\n"+
    "                           BARANGAY CERTIFICATION\n\n\n"+

  "Control No. : " + controlNo + "\n"+
  "Date Issued : " + dateIssued + "\n\n"+

    "   TO WHOM IT MAY CONCERN:\n\n"+

    "          This is to certify that " + fullname + ", a bona fide\n"+
    "  resident of " + address + ", Purok " + purok + ", Barangay\n"+
    "  Basdacu, Loon, Bohol, is personally known to the undersigned\n"+
    "  and is known to be a person of good moral character and a\n"+
    "  law-abiding citizen in the community.\n\n"+

    "         This certification is hereby issued upon the request\n"+
    "  of the above-named person for " + purpose + " and for\n"+
    "  whatever legal purpose it may serve.\n\n"+

    "         Issued this " + day + " day of " + monthYear + " at\n"+
    "  Barangay Basdacu, Loon, Bohol.\n\n\n"+

    "                                     ______________________________\n"+
    "                                         HON. BARANGAY CAPTAIN\n"+
    "                                            Barangay Captain\n"

   

    );


    // ================= DESIGN =================
    report.setFont(
            new Font("Times New Roman", Font.PLAIN, 18)
    );

    report.setEditable(false);

    report.setLineWrap(true);

    report.setWrapStyleWord(true);

    report.setBackground(Color.WHITE);

    report.setMargin(
            new Insets(50,120,50,120)
    );


    // ================= LOGO =================
    ImageIcon logoIcon =
            new ImageIcon("src/ICON/logo_barangay1.png");

    Image img = logoIcon.getImage().getScaledInstance(
            120,
            120,
            Image.SCALE_SMOOTH
    );

    JLabel logo =
            new JLabel(new ImageIcon(img));


    // ================= HEADER PANEL =================
    JPanel headerPanel =
            new JPanel(new BorderLayout());

    headerPanel.setBackground(Color.WHITE);

    logo.setBorder(
            BorderFactory.createEmptyBorder(
                    20,
                    40,
                    10,
                    20
            )
    );


    JLabel heading = new JLabel(

        "<html><center>"
        + "<b>REPUBLIC OF THE PHILIPPINES</b><br>"
        + "Province of Bohol<br>"
        + "Municipality of Loon<br>"
        + "<b>BARANGAY BASDACU</b>"
        + "</center></html>"

    );

    heading.setFont(
            new Font("Times New Roman", Font.BOLD, 20)
    );

    heading.setHorizontalAlignment(
            SwingConstants.CENTER
    );

    heading.setBorder(
            BorderFactory.createEmptyBorder(
                    20,
                    0,
                    10,
                    120
            )
    );


    headerPanel.add(
            logo,
            BorderLayout.WEST
    );

    headerPanel.add(
            heading,
            BorderLayout.CENTER
    );


    // ================= SCROLLPANE =================
          JScrollPane scrollPane =
             new JScrollPane(report);

        scrollPane.setPreferredSize(
        new Dimension(750, 600)
);

        scrollPane.setBorder(null);


    // ================= MAIN PANEL =================
    JPanel panel =
            new JPanel(new BorderLayout());

    panel.setBackground(Color.WHITE);

    panel.add(
            headerPanel,
            BorderLayout.NORTH
    );

    panel.add(
            scrollPane,
            BorderLayout.CENTER
    );


    // ================= SHOW PREVIEW =================
    JOptionPane.showMessageDialog(
            null,
            panel,
            "BARANGAY CERTIFICATE",
            JOptionPane.PLAIN_MESSAGE
    );


    // ================= PRINT =================
    report.print();


    // ================= RELOAD TABLE =================
    loadCertificateRequests();

}catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ADMINDASHBOARD ad = new ADMINDASHBOARD();
ad.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row = certTable.getSelectedRow();

if(row == -1){

    JOptionPane.showMessageDialog(
            null,
            "Select request first."
    );

    return;
}

String fullname =
        certTable.getValueAt(row,0).toString();

String address =
        certTable.getValueAt(row,1).toString();

String purok =
        certTable.getValueAt(row,2).toString();

String certificate =
        certTable.getValueAt(row,3).toString();

String purpose =
        certTable.getValueAt(row,4).toString();

String status = "Done";

try{

    Connection con =
            DBConnection.getConnection();

    // ================= INSERT TO CERTIFICATES =================
    String insertSql =

    "INSERT INTO certificates " +
    "(fullname,address,purok,certificate_type,purpose,status) " +
    "VALUES (?,?,?,?,?,?)";

    PreparedStatement insertPst =
            con.prepareStatement(insertSql);

    insertPst.setString(1, fullname);
    insertPst.setString(2, address);
    insertPst.setString(3, purok);
    insertPst.setString(4, certificate);
    insertPst.setString(5, purpose);
    insertPst.setString(6, status);

    insertPst.executeUpdate();


    // ================= DELETE FROM REQUEST =================
    String deleteSql =

    "DELETE FROM certificate_requests " +
    "WHERE fullname=?";

    PreparedStatement deletePst =
            con.prepareStatement(deleteSql);

    deletePst.setString(1, fullname);

    deletePst.executeUpdate();


    JOptionPane.showMessageDialog(
            null,
            "Certificate Released Successfully."
    );

    loadCertificateRequests();

}catch(Exception e){

    JOptionPane.showMessageDialog(null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void certTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certTableMouseClicked
int row = certTable.getSelectedRow();

String fullname =
        certTable.getValueAt(row,0).toString();

String address =
        certTable.getValueAt(row,1).toString();

String purok =
        certTable.getValueAt(row,2).toString();

String certificate =
        certTable.getValueAt(row,3).toString();

String purpose =
        certTable.getValueAt(row,4).toString();

String status =
        certTable.getValueAt(row,5).toString();


JTextArea.setText(

"CERTIFICATE REQUEST\n\n"+

"Fullname : " + fullname + "\n"+
"Address : " + address + "\n"+
"Purok : " + purok + "\n"+
"Certificate Type : " + certificate + "\n"+
"Purpose : " + purpose + "\n"+
"Status : " + status

);// TODO add your handling code here:
    }//GEN-LAST:event_certTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> new ADMINCERTIFICATE("test").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextArea;
    private javax.swing.JTable certTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
